In [ ]:
import numpy as np
from sklearn import datasets

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


import warnings # sklearn имеет в себе устаревшую часть функций, просто лдоя того чтобы не мешало
warnings.filterwarnings(
    "ignore",
    message="'multi_class' was deprecated",
    category=FutureWarning,
)

# Загружаем данные
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Разделение Признаков
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Маштобирование Признаков
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)


# L1-регуляризация (Lasso)
# Для L1 используем solver 'liblinear', так как стандартный 'lbfgs' её не поддерживает
lr_l1 = LogisticRegression(penalty='l1', C=1.0, solver='liblinear', multi_class='ovr')
lr_l1.fit(X_train_std, y_train)

# L2-регуляризация (Ridge)
# По умолчанию в LogisticRegression используется L2
lr_l2 = LogisticRegression(penalty='l2', C=1.0, solver='lbfgs', multi_class='ovr')
lr_l2.fit(X_train_std, y_train)


Cs = [0.001, 0.01, 0.1, 1, 10]


print("c \t| \t L1 \t | \t L2") # L1 - обнуляет не влияющие | L2 - ошибка считается как квадрат сумы весов, не становится нулём
for c in Cs:
    lr_l1 = LogisticRegression(penalty='l1', C=c, solver='liblinear', multi_class='ovr')
    lr_l1.fit(X_train_std, y_train)
    
    lr_l2 = LogisticRegression(penalty='l2', C=c, solver='lbfgs', multi_class='ovr')
    lr_l2.fit(X_train_std, y_train)
    print(c,"\t|\t",np.sum(lr_l1.coef_==0),"\t | \t",np.sum(lr_l2.coef_==0))
print("+----------------------------+")


c= 0.000001
lr_l1 = LogisticRegression(penalty='l1', C=c, solver='liblinear', multi_class='ovr') # при маленьком C моделе не даётся большая подвижность и стрезается на 0
lr_l1.fit(X_train_std, y_train)


lr_l2 = LogisticRegression(penalty='l2', C=c, solver='lbfgs', multi_class='ovr') # прималеньком си модель бесконечно усеньшает веса стремяс к 0
lr_l2.fit(X_train_std, y_train)

print(lr_l1.coef_,"\n \n",lr_l2.coef_)
    

c 	| 	 L1 	 | 	 L2
0.001 	|	 12 	 | 	 0
0.01 	|	 12 	 | 	 0
0.1 	|	 8 	 | 	 0
1 	|	 4 	 | 	 0
10 	|	 1 	 | 	 0
+----------------------------+
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 
 [[-3.28303990e-05  2.73545697e-05 -4.35339244e-05 -4.15441374e-05]
 [ 8.60948141e-07 -2.53102370e-05  7.34998257e-06  3.18595370e-06]
 [ 3.19687047e-05 -2.04385873e-06  3.61840060e-05  3.83582062e-05]]
